
smart_abbrev_delim = "\\"

smart_abbrev_map = {
  -- Greek letters
  {"Delta"  , "Δ"},
  {"Gamma"  , "Γ"},
  {"Omega"  , "Ω"},
  {"Pi"     , "Π"},
  {"Sigma"  , "Σ"},
  {"Theta"  , "ϴ"},
  {"Theta"  , "ϴ"},
  {"alpha"  , "α"},
  {"beta"   , "β"},
  {"delta"  , "δ"},
  {"epsilon", "ε"},
  {"eta"    , "η"},
  {"gamma"  , "γ"},
  {"lambda" , "λ"},
  {"mu"     , "μ"},
  {"nu"     , "𝜈"},
  {"omega"  , "ω"},
  {"pi"     , "π"},
  {"sigma"  , "σ"},
  {"tao"    , "τ"},
  {"psi"    , "ψ"},
  {"rho"    , "ρ"},
  {"xi"     , "ξ"},
  {"kappa"  , "κ"},
  {"iota"   , "ι"},
  {"zeta"   , "ζ"},

  -- Double struck symbols
  {"Zero" , "𝟘"},
  {"One"  , "𝟙"},
  {"C"    , "ℂ"},
  {"U"    , "𝕌"},
  {"Two"  , "𝟚"},
  {"Three", "𝟛"},
  {"Four" , "𝟜"},
  {"Five" , "𝟝"},
  {"Six", "𝟞"},
  {"Seven", "𝟟"},
  {"Eight", "𝟠"},
  {"Nine", "𝟡"},

  -- Numbers
  {"0", "𝟢"},
  {"1", "𝟣"},

  -- Subscripts
  {"sub0"   , "₀"},
  {"sub1"   , "₁"},
  {"sub2"   , "₂"},
  {"sub3"   , "₃"},
  {"sub4"   , "₄"},
  {"sub5"   , "₅"},
  {"sub6"   , "₆"},
  {"sub7"   , "₇"},
  {"sub8"   , "₈"},
  {"sub9"   , "₉"},
  {"subi"   , "ᵢ"},
  {"subx"   , "ₓ"},
  {"pi1"    , "π₁"},
  {"pi2"    , "π₂"},

  -- Superscripts
  {"sup=" , "⁼"},
  {"sup+" , "⁺"},
  {"sup-" , "⁻"},
  {"sup0" , "⁰"},
  {"sup1" , "¹"},
  {"sup2" , "²"},

  -- Math
  {":="           , "≔"},
  {"exists"       , "∃"},
  {"forall"       , "∀"},
  {"iff"          , "⇔"},
  {"implies"      , "⇒"},
  {"neg"          , "¬"},
  {"and"          , "∧"},
  {"or"           , "∨"},
  {"elem"         , "∈"},
  {"iso"          , "⋍"},
  {"def"          , "≡"},
  {"propersubset" , "⊂"},
  {"crossprod"    , "⨯"},
  {"cp"           , "⨯"},
  {"stprod"       , "☓"},
  {"Real"         , "ℝ"},
  {"Int"          , "ℤ"},
  {"Nat"          , "ℕ"},
  {"inf"          , "∞"},
  {"gte"          , "≥"},
  {"gte'"         , "≽"},
  {"lte"          , "≤"},
  {"lte'"         , "≼"},
  {"notelem"      , "∉"},
  {"empty"        , "∅"},
  {"subset"       , "⊆"},
  {"maplet"       , "↦"},
  {"bottom"       , "⊥"},
  {"top"          , "⊤"},
  {"union"        , "∪"},
  {"disjointunion", "⊔"},
  {"dunion"       , "⊔"},
  {"du"           , "⊔"},
  {"dp"           , "⊓"},
  {"intersect"    , "∩"},
  {"ring"         , "∘"},
  {"tensorsum"    , "⊕"},
  {"tensorprod"   , "⊗"},
  {"neq"          , "≠"},
  {"->"           , "→"},
  {"<="           , "⇐"},
  {"=>"           , "⇒"},
  {"qed"          , "∎"},
  {"+-"           , "±"},
  {"lol"          , "⊸"},
  {"dotprod"      , "·"},
  {"turn"         , "⊦"},
  {"~>"           , "⇝"},
  {"->>"          , "⇾"},

  -- Brackets
  {"leftangle" , "⟨"},
  {"<"         , "⟨"},
  {"rightangle", "⟩"},
  {">"         , "⟩"},
  {"<|"        , "⟪"},
  {"|>"        , "⟫"},

  -- Miscelaneous
  {"up"            , "↑"},
  {"down"          , "↓"},
  {"left"          , "←"},
  {"right"         , "→"},
  {"downright"     , "↳"},
  {"tick"          , "✔"},
  {"cross"         , "✗"},
  {"prime"         , "′"},
  {"`"             , "‘"},
  {"'"             , "‛"},
  {"~"             , "˜"},
  {"ntilde"        , "≁"},

  -- Combining marks
  -- Acute accent
  {"acac"          , "́"},
  {"macron"        , "̄"},
  {"dot"           , "̇"}
}
